[package]
name = "image-cropper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
glob = "0.3.1"
image = "0.25.1"
num_cpus = "1.16"
rayon = "1.10"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false
